/**
 * Wrapper Generator for Stargazer v2
 *
 * Generates real .astro wrapper pages for each component.
 * These are genuine Astro pages that import the component and its layout
 * statically, so Astro's full compilation pipeline (scoped styles, asset
 * resolution, content collections, scripts) works natively.
 */

import type { ResolvedComponent, StargazerConfig } from './types.js';
import { mkdirSync, writeFileSync, existsSync, rmSync, readdirSync } from 'node:fs';
import { join, dirname } from 'node:path';

function normalizePath(p: string): string {
  return p.replace(/\\/g, '/');
}

/**
 * Convert a component/layout path (like `./src/components/Foo.astro` or `/src/layouts/Layout.astro`)
 * to an absolute import path from project root (like `/src/components/Foo.astro`).
 * Vite resolves bare `/` imports from the project root.
 */
function toRootImport(filePath: string): string {
  let clean = normalizePath(filePath);
  // Strip leading ./ 
  if (clean.startsWith('./')) clean = clean.slice(2);
  // Ensure leading /
  if (!clean.startsWith('/')) clean = '/' + clean;
  return clean;
}

/**
 * Serialize a props object into a JavaScript expression string
 * that can be placed in an Astro frontmatter block.
 */
function serializeProps(props: Record<string, unknown>): string {
  // Filter out undefined values
  const filtered: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(props)) {
    if (value !== undefined) filtered[key] = value;
  }
  if (Object.keys(filtered).length === 0) return '{}';
  return JSON.stringify(filtered, null, 2);
}

/**
 * Generate the .astro source for a wrapper page.
 */
function generateWrapperSource(
  comp: ResolvedComponent,
  config: StargazerConfig,
  globalCssImports: string[]
): string {
  const componentImport = toRootImport(comp.componentPath);
  const layoutImport = comp.layoutPath ? toRootImport(comp.layoutPath) : null;
  const propsStr = serializeProps(comp.props);

  // Build the frontmatter
  const imports: string[] = [];
  if (layoutImport) {
    imports.push(`import Layout from '${layoutImport}';`);
  }
  imports.push(`import Component from '${componentImport}';`);

  // Import global CSS — but only if NOT using a layout (the layout already imports CSS)
  // OR if explicit globalCss is configured
  if (config.globalCss && Array.isArray(config.globalCss)) {
    for (const css of config.globalCss) {
      imports.push(`import '${toRootImport(css)}';`);
    }
  } else if (!layoutImport) {
    // No layout — import discovered CSS so the component isn't unstyled
    for (const css of globalCssImports) {
      imports.push(`import '${css}';`);
    }
  }

  const frontmatter = [
    '---',
    '// Auto-generated by Stargazer — DO NOT EDIT',
    'export const prerender = false;',
    '',
    ...imports,
    '',
    `const __props = ${propsStr};`,
    '---',
  ].join('\n');

  // Build the template — wrap Component in data-sg-keep so the
  // overlay suppressor knows which DOM belongs to the previewed component
  let template: string;
  if (layoutImport) {
    template = [
      '<Layout {...__props}>',
      '  <div data-sg-keep>',
      '    <Component {...__props} />',
      '  </div>',
      '</Layout>',
    ].join('\n');
  } else {
    template = '<div data-sg-keep>\n  <Component {...__props} />\n</div>';
  }

  const darkModeJson = JSON.stringify(config.darkMode || {});

  // ── Overlay / Popup Suppressor ─────────────────────────────────────
  // Only uses lightweight CSS for body scroll-lock prevention.
  // All overlay detection is done by the JS runtime heuristic which
  // checks viewport coverage + z-index + position:fixed/absolute and
  // respects data-sg-keep ancestry (= the component being previewed).
  const overlayCSS = `
<style is:global>
  /* ── Stargazer Preview Isolation ───────────────────────────────── */
  /* Prevent body scroll lock that modals/overlays often set */
  html[data-sg-preview] body {
    overflow: auto !important;
    position: static !important;
  }
  /* Allow Stargazer Light/Dark theme toggle to control the canvas background */
  html[data-sg-preview][data-theme="light"] body {
    background-color: #EFEDE8 !important;
    color: #272220;
  }
  /* data-sg-keep wrapper should be invisible */
  [data-sg-keep] {
    display: contents;
  }
</style>`;

  const clientScripts = `
${overlayCSS}
<script is:inline define:vars={{ darkModeJson: ${JSON.stringify(darkModeJson)} }}>
  window.__stargazerDarkMode = JSON.parse(darkModeJson);
  // Mark document as a Stargazer preview immediately
  document.documentElement.setAttribute('data-sg-preview', 'true');
</script>
<script is:inline>
  // ── Stargazer Origin Tagger ──────────────────────────────────────
  // Tag all elements belonging to the previewed component immediately.
  // This ensures that if client scripts teleport modals/popups/lightboxes
  // to document.body, Stargazer knows they belong to the component and does NOT hide them.
  (function() {
    function tagElements() {
      var keep = document.querySelector('[data-sg-keep]');
      if (keep) {
        var els = keep.querySelectorAll('*');
        for (var i = 0; i < els.length; i++) {
          els[i].setAttribute('data-sg-origin', 'true');
        }
      }
    }
    tagElements();
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', tagElements);
    }
    // Intercept teleportation to document.body
    if (typeof Element !== 'undefined' && Element.prototype.appendChild) {
      var origAppend = Element.prototype.appendChild;
      Element.prototype.appendChild = function(child) {
        if (child && child.nodeType === 1) {
          if (child.hasAttribute('data-sg-origin') || (child.closest && child.closest('[data-sg-keep]'))) {
            child.setAttribute('data-sg-origin', 'true');
          }
        }
        return origAppend.apply(this, arguments);
      };
    }
  })();
</script>
<script is:inline src="/__stargazer_controls.js"></script>
<script is:inline>
  // ── Stargazer Overlay Suppressor (Runtime) ────────────────────────
  // Phase 2: Detect and hide site-wide overlays (cookie banners, full-page modals from Layout)
  // while preserving anything that belongs to the previewed component.
  (function() {
    var VIEWPORT_THRESHOLD = 0.25; // hide if covers >25% of viewport
    var ZINDEX_THRESHOLD = 50;
    var suppressed = new WeakSet();

    function isPartOfComponent(el) {
      // Elements with data-sg-keep or data-sg-origin are explicitly preserved
      if (el.hasAttribute('data-sg-keep') || el.hasAttribute('data-sg-origin')) return true;
      if (el.closest && (el.closest('[data-sg-keep]') || el.closest('[data-sg-origin]'))) return true;
      // Walk up — if any parent has data-sg-keep or data-sg-origin, preserve it
      var p = el.parentElement;
      while (p) {
        if (p.hasAttribute('data-sg-keep') || p.hasAttribute('data-sg-origin')) return true;
        p = p.parentElement;
      }
      return false;
    }

    function suppressOverlays() {
      var vw = window.innerWidth || document.documentElement.clientWidth;
      var vh = window.innerHeight || document.documentElement.clientHeight;
      var vpArea = vw * vh;
      if (vpArea === 0) return;

      // Check all elements with position fixed or absolute
      var candidates = document.querySelectorAll('*');
      for (var i = 0; i < candidates.length; i++) {
        var el = candidates[i];
        if (suppressed.has(el)) continue;
        if (isPartOfComponent(el)) continue;

        var cs = getComputedStyle(el);
        var pos = cs.position;
        if (pos !== 'fixed' && pos !== 'absolute') continue;

        var z = parseInt(cs.zIndex, 10);
        if (isNaN(z) || z < ZINDEX_THRESHOLD) continue;

        // Check viewport coverage
        var rect = el.getBoundingClientRect();
        var elArea = rect.width * rect.height;
        var coverage = elArea / vpArea;

        if (coverage > VIEWPORT_THRESHOLD && rect.width > vw * 0.5) {
          el.style.setProperty('display', 'none', 'important');
          el.style.setProperty('visibility', 'hidden', 'important');
          el.style.setProperty('pointer-events', 'none', 'important');
          suppressed.add(el);
        }
      }
    }

    // Also suppress <dialog> elements that get opened
    function suppressDialogs() {
      var dialogs = document.querySelectorAll('dialog[open]');
      for (var i = 0; i < dialogs.length; i++) {
        if (!isPartOfComponent(dialogs[i]) && !suppressed.has(dialogs[i])) {
          dialogs[i].close();
          suppressed.add(dialogs[i]);
        }
      }
    }

    // Force the previewed component to be visible.
    // Many components (cookie banners, modals, tooltips) start hidden
    // (display:none) and rely on JS to activate them. In Stargazer
    // previews we force the component root visible so the user can see it.
    var SKIP_TAGS = {SCRIPT:1,STYLE:1,LINK:1,TEMPLATE:1,NOSCRIPT:1,META:1};
    function forceComponentVisible() {
      var containers = document.querySelectorAll('[data-sg-keep]');
      for (var i = 0; i < containers.length; i++) {
        var children = containers[i].children;
        for (var j = 0; j < children.length; j++) {
          var el = children[j];
          if (SKIP_TAGS[el.tagName]) continue;
          var cs = getComputedStyle(el);
          if (cs.display === 'none') {
            el.style.setProperty('display', 'block', 'important');
          }
          if (cs.visibility === 'hidden') {
            el.style.setProperty('visibility', 'visible', 'important');
          }
          if (parseFloat(cs.opacity) === 0) {
            el.style.setProperty('opacity', '1', 'important');
          }
        }
      }
    }

    function runAll() {
      forceComponentVisible();
      suppressOverlays();
      suppressDialogs();
    }

    // Run on DOMContentLoaded, load, and periodically for the first 5s
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', runAll);
    } else {
      runAll();
    }
    window.addEventListener('load', function() {
      runAll();
      setTimeout(runAll, 300);
      setTimeout(runAll, 800);
      setTimeout(runAll, 1500);
      setTimeout(runAll, 3000);
      setTimeout(runAll, 5000);
    });

    // MutationObserver: catch dynamically injected overlays
    if (typeof MutationObserver !== 'undefined') {
      var debounceTimer;
      var observer = new MutationObserver(function() {
        clearTimeout(debounceTimer);
        debounceTimer = setTimeout(runAll, 100);
      });
      observer.observe(document.documentElement, {
        childList: true,
        subtree: true,
        attributes: true,
        attributeFilter: ['class', 'style', 'open']
      });
    }
  })();

  // ── Height Reporter ───────────────────────────────────────────────
  function sgReportHeight() {
    var h = Math.max(document.documentElement.scrollHeight, document.body ? document.body.scrollHeight : 0);
    if (h > 50) parent.postMessage({ type: 'sg-resize', height: h }, '*');
  }
  window.addEventListener('load', function() {
    sgReportHeight();
    setTimeout(sgReportHeight, 500);
    setTimeout(sgReportHeight, 1500);
  });
</script>`;

  return `${frontmatter}\n\n${template}\n${clientScripts}\n`;
}

/**
 * Generate wrapper .astro files for all components.
 * Returns a map of slug → absolute path to the wrapper file.
 */
export function generateWrappers(
  components: ResolvedComponent[],
  config: StargazerConfig,
  projectRoot: string,
  globalCssImports: string[] = []
): Map<string, string> {
  const wrappersDir = join(projectRoot, '.stargazer', 'previews');

  // Auto-discover global CSS if not provided
  if (globalCssImports.length === 0 && projectRoot) {
    for (const dir of ['src/css', 'src/styles', 'src']) {
      const absDir = join(projectRoot, dir);
      if (existsSync(absDir)) {
        try {
          for (const file of readdirSync(absDir)) {
            if ((file.endsWith('.css') || file.endsWith('.scss')) && !file.includes('node_modules')) {
              const relPath = `/${dir}/${file}`.replace(/\/\/+/g, '/');
              if (!globalCssImports.includes(relPath)) globalCssImports.push(relPath);
            }
          }
        } catch { }
      }
    }
  }

  // Clean and recreate the directory
  if (existsSync(wrappersDir)) {
    rmSync(wrappersDir, { recursive: true, force: true });
  }
  mkdirSync(wrappersDir, { recursive: true });

  const slugToPath = new Map<string, string>();

  for (const comp of components) {
    const source = generateWrapperSource(comp, config, globalCssImports);
    const wrapperPath = join(wrappersDir, `${comp.slug}.astro`);
    writeFileSync(wrapperPath, source, 'utf-8');
    slugToPath.set(comp.slug, normalizePath(wrapperPath));
  }

  // Write a .gitignore in .stargazer/ to prevent committing generated files
  const gitignorePath = join(projectRoot, '.stargazer', '.gitignore');
  writeFileSync(gitignorePath, '*\n', 'utf-8');

  return slugToPath;
}

export type { ResolvedComponent, StargazerConfig };
